### ISSUE TITLE
error Error: Error while resuming the upload

### ISSUE THREAD

**Issue by ruballos** [vinzscam/react-native-tus-client#1]
When I close the App and open again....in create a func to continue the Upload with the same file source....but I got this error and the Upload start in 0% again:

```
error Error: Error while resuming the upload
    at posicionpicker.js:51
    at MessageQueue.__invokeCallback (MessageQueue.js:400)
    at MessageQueue.js:139
    at MessageQueue.__guardSafe (MessageQueue.js:316)
    at MessageQueue.invokeCallbackAndReturnFlushedQueue (MessageQueue.js:138)
    at debuggerWorker.js:72
```

Can you help me?

**Comment by vinzscam** [comment]
Hi @ruballos,
Check the new version.
Let me know if that works!

**Comment by ruballos** [comment]
Thanks!!! Now this works for me :)
A question...It´s possible close the App...and open again the App resuming the Upload? When I try it, the Upload start in 0%...how I would save the 'session' with my tus server (I think...when I open the App and create a new Upload() the previous object is replaced with the new Upload instance....and the previous session is erased)¿?

**Comment by michaelost** [comment]
@ruballos , I am struggling against making it send a file. could you please share the working code ? would be very grateful

**Comment by Usamaliaquat123** [comment]
@ruballos    
onProgress: (uploaded, total) => console.log(
    `Progress: ${(uploaded/total*100)|0}%`)
