### ISSUE TITLE
No such file or directory Error

### ISSUE THREAD

**Issue by AbbasNarimani** [vinzscam/react-native-tus-client#10]
Hello everyone;
I want to use tus-client to upload my videos on a remote endpoint. but after choosing a video from my android device and when I start upload it shows an Error which says 
 Failed because: Error: file:/storage/emulated/0/Movies/c5326f6c-dc42-4eb0-97c8-040233f08352.mp4 (No such file or directory)
is there any solution for that or could you help me to find the right way for uploading my files?
best regards;

my react-native version is 0.60.6
the video uri is like: file:/storage/emulated/0/Movies/c5326f6c-dc42-4eb0-97c8-040233f08352.mp4
and the way I'm trying to send my files is:

  let uploadOptions = {
    "url": `my_EndpointUri`,
    "authorization": `${authorization_key}`,
    "acceptLanguage": 'en',
    "uuid": "salam"//ImageUri.name + ImageUri.size + ImageUri.lastModified,
  };
  const upload = new Upload(ImageUri, {
    fingerprint: () => {
      return uploadOptions.uuid;
    },
    resume: true,
    chunkSize: 1048576, // 1MB
    retryDelays: [0, 500, 1000, 1500, 2000, 2500],
    endpoint: uploadOptions.url, 
    headers: {
      'Authorization': uploadOptions.authorization,
      'Accept-Language': uploadOptions.acceptLanguage,
    },
    metadata: {
      filename: "video.mp4",
      filetype: "video/mp4"
    },
    onError: function (error) {
      console.log("Failed because: " + error)
    },
    onProgress: function (bytesUploaded, bytesTotal) {
      var percentage = (bytesUploaded / bytesTotal * 100).toFixed(2)
      console.log(bytesUploaded, bytesTotal, percentage + "%")
    },
    onSuccess: function () {
      console.log("Download %s from %s", upload.file.name, upload.url)
    }
  });
  await upload.start();
}

**Comment by HarishJangra** [comment]
@AbbasNarimani  Did you get it  to work?? i need help facing same issue.

**Comment by AbbasNarimani** [comment]
sorry for late answer.
just left it and used react js package. now it works very well.
https://github.com/tus/tus-js-client

**Comment by vinzscam** [comment]
@AbbasNarimani I believe your issue was related to the original file path.
@HarishJangra if you're facing a similar issue, please post your snippet as well with information about your RN version and device/simulator you are using.

**Comment by HarishJangra** [comment]
yes actually i fixed it to work with vimeo support in this commit 76592360aa1a21195063d59063e3188ce11004d0

**Comment by vinzscam** [comment]
thanks for sharing @HarishJangra. True, Vimeo has a different way of handling tus file upload creation. I will pass an extra option for handling this specific case.

**Comment by oleg-moseyko** [comment]
have the same issue:
absoluteFilePath file:///storage/emulated/0/Download/brooke-cagle-pJqfhKUpCh8-unsplash.jpg

const upload = new Upload(absoluteFilePath, options);
            upload.start();

TSU Upload error [Error: file:/storage/emulated/0/Download/brooke-cagle-pJqfhKUpCh8-unsplash.jpg (No such file or directory)]
