### ISSUE TITLE
Can't build with iOs...!  NOT WORKING

### ISSUE THREAD

**Issue by iqbalfaisal** [vinzscam/react-native-tus-client#5]
<img width="1280" alt="Screen Shot 2019-09-06 at 3 09 40 PM" src="https://user-images.githubusercontent.com/46706064/64420360-8c6ca100-d0b8-11e9-8ef0-03fb8f271391.png">

can't found any solution.

Please resolve this asap so I wrap-up app

**Comment by iqbalfaisal** [comment]
Guys please review that. I need an urgent response on that , client is waiting for next build

**Comment by chocolateonly** [comment]
Hi @faisalrajput ,
I have the same problem as you. How did you solve it?

**Comment by vinzscam** [comment]
This should be fixed now. Please download version `1.1.0` and follow the new linking instruction:

```
# RN >= 0.60
cd ios && pod install

# RN < 0.60
react-native link react-native-tus-client
```
